# Generated by Django 5.2.11 on 2026-02-23 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii_aide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='admission_clause_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='admission_questionnaire',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='appointment',
            name='admission_support_in_subscription',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='decision_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='evaluation_type',
            field=models.CharField(blank=True, choices=[('ONLINE_CALL', 'Online Call'), ('PHYSICAL_VISIT', 'Physical Visit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='shift_type',
            field=models.CharField(choices=[('DAILY_PER_HOUR_12H', 'Daily Per Hour - 12 Hrs'), ('LIVE_IN_24H', 'Live In - 24 Hrs')], default='DAILY_PER_HOUR_12H', max_length=30),
        ),
        migrations.AddField(
            model_name='appointment',
            name='suggested_nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_appointments', to='jamii_aide.healthcarenurse'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='nurse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='jamii_aide.healthcarenurse'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('NURSE_SUGGESTED', 'Nurse Suggested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='SUBMITTED', max_length=20),
        ),
    ]
