# Generated by Django 5.2.11 on 2026-02-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii_aide', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcarenurse',
            name='professional_type',
            field=models.CharField(choices=[('PHYSIOTHERAPIST', 'Physiotherapist'), ('CAREGIVER_NURSE', 'Caregiver Nurse'), ('PALLIATIVE_CARE_NURSE', 'Palliative Care Nurse')], db_index=True, default='CAREGIVER_NURSE', max_length=30),
        ),
        migrations.AddIndex(
            model_name='healthcarenurse',
            index=models.Index(fields=['professional_type'], name='healthcare__profess_17532a_idx'),
        ),
    ]
