# Generated by Django 5.2.11 on 2026-02-24 07:27

from django.db import migrations, models


def migrate_diaspora_to_end_user(apps, schema_editor):
    CustomUser = apps.get_model('jamii_aide', 'CustomUser')
    CustomUser.objects.filter(role='DIASPORA_USER').update(role='END_USER')


def rollback_end_user_to_diaspora(apps, schema_editor):
    CustomUser = apps.get_model('jamii_aide', 'CustomUser')
    CustomUser.objects.filter(role='END_USER').update(role='DIASPORA_USER')


class Migration(migrations.Migration):

    dependencies = [
        ('jamii_aide', '0004_healthcarenurse_professional_type_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_diaspora_to_end_user, rollback_end_user_to_diaspora),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('END_USER', 'End User'), ('DIASPORA_USER', 'Diaspora User (Legacy)'), ('HEALTHCARE_NURSE', 'Healthcare Nurse'), ('ADMIN', 'Administrator')], default='END_USER', max_length=20),
        ),
    ]
