# Generated by Django 5.2.11 on 2026-02-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jamii_aide', '0006_unify_end_user_naming'),
    ]

    operations = []
