# Generated by Django 5.2.11 on 2026-02-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii_aide', '0006_unify_end_user_naming'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_diaspor_fc9994_idx',
        ),
        migrations.RemoveIndex(
            model_name='familymember',
            name='family_memb_diaspor_5b6285_idx',
        ),
        migrations.RemoveIndex(
            model_name='healthrecord',
            name='health_reco_diaspor_88f4f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_diaspor_4ee1ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_diaspor_04ca77_idx',
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['end_user_profile'], name='appointment_end_use_a92f86_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['end_user_profile'], name='family_memb_end_use_3c9703_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['end_user_profile'], name='health_reco_end_use_31a0b5_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['end_user_profile'], name='payments_end_use_a3a40a_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['end_user_profile'], name='prescriptio_end_use_d014ca_idx'),
        ),
    ]
