# Generated by Django 4.2.10 on 2026-03-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jamii_aide', '0007_remove_appointment_appointment_diaspor_fc9994_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
