# Generated by Django 4.2.10 on 2026-07-27 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("jamii_aide", "0011_backfill_pending_nurses"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationAdministrator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_title", models.CharField(blank=True, max_length=120, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="administrators",
                        to="jamii_aide.organization",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organization_admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Administrator",
                "verbose_name_plural": "Organization Administrators",
                "db_table": "organization_administrators",
            },
        ),
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("nurse", "Nurse"),
                    ("admin", "Admin"),
                    ("organization_admin", "Organization Administrator"),
                ],
                default="user",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["name"], name="organizatio_name_5cd1d4_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(fields=["code"], name="organizatio_code_c5d604_idx"),
        ),
        migrations.AddIndex(
            model_name="organization",
            index=models.Index(
                fields=["is_active"], name="organizatio_is_acti_bdc355_idx"
            ),
        ),
        migrations.AddField(
            model_name="healthcarenurse",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="nurses",
                to="jamii_aide.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="healthcarenurse",
            index=models.Index(
                fields=["organization"], name="healthcare__organiz_03af90_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationadministrator",
            index=models.Index(
                fields=["organization"], name="organizatio_organiz_e5f09d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationadministrator",
            index=models.Index(
                fields=["is_active"], name="organizatio_is_acti_0fb6c1_idx"
            ),
        ),
    ]
