# Generated by Django 4.2.10 on 2026-08-17 06:13

from django.db import migrations, models
import jamii_aide.models


class Migration(migrations.Migration):

    dependencies = [
        ("jamii_aide", "0014_notification_event_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="end_user_profile",
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[
                ("objects", jamii_aide.models.CustomUserManager()),
            ],
        ),
        migrations.RenameIndex(
            model_name="healthcarenurse",
            new_name="healthcare__organiz_03af90_idx",
            old_name="healthcare_n_organiz_88bf59_idx",
        ),
        migrations.RenameIndex(
            model_name="organization",
            new_name="organizatio_name_5cd1d4_idx",
            old_name="organizatio_name_67a572_idx",
        ),
        migrations.RenameIndex(
            model_name="organization",
            new_name="organizatio_is_acti_bdc355_idx",
            old_name="organizatio_is_acti_ec5684_idx",
        ),
        migrations.RenameIndex(
            model_name="organizationadministrator",
            new_name="organizatio_organiz_e5f09d_idx",
            old_name="organizatio_organiz_9ca8eb_idx",
        ),
        migrations.AlterField(
            model_name="healthrecord",
            name="type",
            field=models.CharField(
                choices=[
                    ("APPOINTMENT_NOTES", "Appointment Notes"),
                    ("LAB_RESULT", "Lab Result"),
                    ("VITAL_SIGNS", "Vital Signs"),
                    ("DIAGNOSIS", "Diagnosis"),
                    ("GENERAL_NOTE", "General Note"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
    ]
