# Generated by Django 4.2.10 on 2026-08-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamii_aide", "0015_remove_prescription_end_user_profile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="provider_reference",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="redirect_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("MPESA", "M-Pesa"),
                    ("CARD", "Card"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("PESAPAL", "PesaPal"),
                ],
                max_length=20,
            ),
        ),
    ]
