# Generated by Django 4.2.10 on 2026-08-31 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamii_aide", "0016_payment_provider_reference_payment_redirect_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
